@startuml
/'-------------- Style ----------------'/
skinparam roundcorner 20
skinparam class {
	BackgroundColor Moccasin
	ArrowColor Maroon
	BorderColor Purple
}
skinparam stereotypeCBackgroundColor YellowGreen
/'---------------------------------------'/

/'-------------- TestcasesComponent ----------------'/
'namespace muteria.drivers.testgeneration #DDDDDD {
package muteria.drivers.testcasescomponent #DDEDD0 {
    class TestsInfoObject
    class MetaTestcaseTool
    abstract class BaseTestcaseTool
    package languages.[language].[testcasetool] #DDEDEE{
       class StaticTestcaseTool 
       class DynamicTestcaseTool 
    }
    class "      " as Hook_TestTool
    hide Hook_TestTool fields 
    hide Hook_TestTool methods 
    hide Hook_TestTool circle 
    note right of Hook_TestTool #white\FFFFFE
        Each plugged-in 
        testcase tool    
    end note

    StaticTestcaseTool -- Hook_TestTool
    DynamicTestcaseTool -- Hook_TestTool
    Hook_TestTool --|> BaseTestcaseTool : extends >
    Hook_TestTool "1..*" --* "1" MetaTestcaseTool : < manages
    TestsInfoObject "1" -* "1" BaseTestcaseTool
    MetaTestcaseTool "1" *- "1" TestsInfoObject 
}
MetaTestcaseTool --() TestcasesManager 
'muteria.drivers.testcasescomponent +-- languages.<<language>>.<<testtool>>

' Other components dependences
/'---------------------------------------'/

/'-------------- CodecoverageComponent ----------------'/
package muteria.drivers.codecoveragecomponent #EDDDD0 {
    class CodeInfoObject
    class MetaCodecoverageTool
    abstract class BaseCodecoverageTool
    package languages.[language].[codecoveragetool] #EDDDEE{
       class CodecoverageTool 
    }
    class "      " as Hook_CodecovTool
    hide Hook_CodecovTool fields 
    hide Hook_CodecovTool methods 
    hide Hook_CodecovTool circle 
    note right of Hook_CodecovTool #white\FFFFFE
        Each plugged-in 
        codecoverage tool    
    end note

    CodecoverageTool -- Hook_CodecovTool
    Hook_CodecovTool --|> BaseCodecoverageTool : extends >
    Hook_CodecovTool "1..*" --* "1" MetaCodecoverageTool : < manages
    CodeInfoObject "1" -* "1" BaseCodecoverageTool
    MetaCodecoverageTool "1" *- "1" CodeInfoObject 
}
MetaCodecoverageTool --() CodecoverageManager 

' Other components dependences
MetaCodecoverageTool o-- MetaTestcaseTool 
/'---------------------------------------'/

/'-------------- MutantionComponent ----------------'/
package muteria.drivers.mutationcomponent #DDDDEE {
    class MutantsInfoObject
    class MetaMutationTool
    abstract class BaseMutationTool
    package languages.[language].[mutationtool] #CDDDFF{
       class MutationTool 
    }
    class "      " as Hook_MutationTool
    hide Hook_MutationTool fields 
    hide Hook_MutationTool methods 
    hide Hook_MutationTool circle 
    note left of Hook_MutationTool #white\FFFFFE
        Each plugged-in 
        mutation tool    
    end note

    MutationTool -- Hook_MutationTool
    Hook_MutationTool --|> BaseMutationTool : extends >
    Hook_MutationTool "1..*" --* "1" MetaMutationTool : < manages
    BaseMutationTool "1" *- "1" MutantsInfoObject
    MutantsInfoObject "1" -* "1" MetaMutationTool 
}
MetaMutationTool --() MutationManager 

' Other components dependences
MetaTestcaseTool --o MetaMutationTool
/'---------------------------------------'/

/'-------------- TestGenerationGuidanceComponent ----------------'/
package muteria.drivers.testgenerationguidancecomponent #DDDDA0 {
    class MetaTestcaseGenerationGuidanceTool
    abstract class BaseTestcaseGenerationGuidanceTool
    package languages.[language].[testcaseguidancetool] #DDFDAE{
       class TestcaseGenerationGuidanceTool 
    }

    TestcaseGenerationGuidanceTool --|> BaseTestcaseGenerationGuidanceTool: extends >
    TestcaseGenerationGuidanceTool "1..*" --* "1" MetaTestcaseGenerationGuidanceTool : < manages
}
MetaTestcaseGenerationGuidanceTool --() TestcaseGenerationGuidanceManager 

' Other components dependences
'MetaTestcaseTool o-- MetaTestcaseGenerationGuidanceTool
/'---------------------------------------'/

/'-------------- TestcaseExecutionOPtimizationComponent ----------------'/
package muteria.drivers.testcaseexecutionoptimizationcomponent #DDDCC0 {
    class MetaTestcaseExecutionOptimizerTool
    abstract class BaseTestcaseExecutionOptimizerTool
    package languages.[language].[testcaseoptimizertool] #DDFDEE{
       class TestcaseExecutionOptimizerTool 
    }

    TestcaseExecutionOptimizerTool --|> BaseTestcaseExecutionOptimizerTool : extends >
    TestcaseExecutionOptimizerTool "1..*" --* "1" MetaTestcaseExecutionOptimizerTool : < manages
}
MetaTestcaseExecutionOptimizerTool --() TestcaseOptimizerManager 

' Other components dependences
'MetaTestcaseTool o-- MetaTestcaseExecutionOptimizerTool
/'---------------------------------------'/

/'-------------- MutantPrioritizationSelectionComponent ----------------'/
package muteria.drivers.mutatantexecutionoptimizationcomponent #DEDDDD {
    class MetaMutantExecutionOptimizerTool
    abstract class BaseMutantExecutionOptimizerTool
    package languages.[language].[mutantexecutionoptimizertool] #DFDDEE{
       class MutantExecutionOptimizerTool 
    }

    MutantExecutionOptimizerTool --|> BaseMutantExecutionOptimizerTool : extends >
    MutantExecutionOptimizerTool "1..*" --* "1" MetaMutantExecutionOptimizerTool : < manages
}
MetaMutantExecutionOptimizerTool --() MutantExecutionOptimizerManager 

' Other components dependences
'MetaMutationTool o-- MetaMutantExecutionOptimizerTool 
/'---------------------------------------'/

/'------------- Beautify the layout ------------------'/
'muteria.drivers.mutatantexecutionoptimizationcomponent --[hidden]-- 
'muteria.drivers.testcasescomponent --[hidden]-- muteria.drivers.mutationcomponent
'muteria.drivers.codecoveragecomponent --[hidden]-- muteria.drivers.testcasescomponent
'muteria.drivers.codecoveragecomponent --[hidden]-- muteria.drivers.mutationcomponent
muteria.drivers.testgenerationguidancecomponent --[hidden]-- muteria.drivers.testcaseexecutionoptimizationcomponent 
muteria.drivers.testcaseexecutionoptimizationcomponent --[hidden]-- muteria.drivers.mutatantexecutionoptimizationcomponent
muteria.drivers.testcasescomponent --[hidden]-- muteria.drivers.mutatantexecutionoptimizationcomponent
/'----------------------------------------------------'/
@enduml