@startuml
/'-------------- Style ----------------'/
skinparam roundcorner 20
skinparam class {
	BackgroundColor Moccasin
	ArrowColor Maroon
	BorderColor Purple
}
skinparam stereotypeCBackgroundColor YellowGreen
/'---------------------------------------'/
start
stop
@enduml